## Date: 09/02/2023

In [32]:
import numpy as np
import pandas as pd

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.svm import SVC

In [2]:
print("numpy version: ", np.__version__)
print("pandas version: ", pd.__version__)
print("sklearn version: ", sklearn.__version__)

# numpy version:  1.24.1
# pandas version:  1.5.2
# sklearn version:  1.2.1

numpy version:  1.24.1
pandas version:  1.5.2
sklearn version:  1.2.1


### Equation of the Hyperplane:

`y = wx - b`

### Gradient Descent:

Gradient Descent is an optimization algorithm used for minimizing the loss function in various machine learning algorithms. It is used for updating the parameters of the learning model.

`w = w - α*dw`

`b = b - α*db`

### Learning Rate:

Learning rate is a tuning parameter in an optimization algorithm that determines the step size at each iteration while moving toward a minimum of a loss function.

#### Let's create svm classifier

In [3]:
class SVMC:
    def __init__(self, learning_rate=0.01, epochs=100, lambda_value=0.1):
        self.lr = learning_rate
        self.epochs = epochs
        self.c = lambda_value
        self.intercept_ = None
        self.coef_ = None
    
    def fit(self, X, y):
        
        self.intercept_ = 0
        self.coef_ = np.ones(X.shape[1])
        
        # label encoding. we done it because we know svm only know 1(+ve) and -1(-ve) to seperate the classes
        y_hate = np.where(y<=0, -1, 1) # where(condition, if true, if false)
        
        for i in range(self.epochs):
            for index_val, x_value in enumerate(X):
                condition = y_hate[index_val] * (np.dot(a=x_value, b=self.coef_) - self.intercept_) >= 1
                
                if condition == True:
                    dw = 2 * self.c * self.coef_
                    db = 0
                    
                else:
                    dw = (2 * self.c * self.coef_) - np.dot(a=x_value, b=y_hate[index_val])
                    db = y_hate[index_val]
                
                # now update the weights
                self.coef_ = self.coef_ - self.lr * dw
                self.intercept_ = self.intercept_ - self.lr * db
                
    
    def predict(self, X):
        # it will give any +ve and -ve value
        y_pred = np.dot(a=X, b=self.coef_) - self.intercept_
        # np.sign() used for convert all value in -1 and +1
        y_pred = np.where(np.sign(y_pred)<=-1, 0, 1)
        
        return y_pred

### Load data

In [4]:
df = pd.read_csv("dataset/diabetes.csv")

df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
df.shape

(768, 9)

In [6]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [7]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [8]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
# Spliting the data

X = df.iloc[:, 0:-1]

y = df.iloc[:, -1]

In [10]:
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [11]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=11)

In [13]:
X_train.shape

(614, 8)

In [14]:
X_test.shape

(154, 8)

In [15]:
y_train.shape

(614,)

In [16]:
scaler = StandardScaler()

In [17]:
X_train_scale = scaler.fit_transform(X=X_train)
X_test_scale = scaler.transform(X=X_test)

In [18]:
X_train_scale

array([[ 1.54556941, -1.00773197, -0.35850598, ..., -1.23149461,
        -0.99091368, -0.00950951],
       [ 1.54556941,  1.58619897,  2.15001451, ...,  1.73050492,
         0.72537813,  1.79366231],
       [ 0.35225961,  0.47903333,  0.79123258, ...,  0.38531736,
        -0.5640639 ,  0.16222114],
       ...,
       [ 0.35225961, -0.78629884,  0.26862414, ...,  0.20423442,
         1.54350686,  0.84914374],
       [ 0.35225961, -0.28016597, -0.14946261, ...,  0.74748325,
        -0.63816977,  0.67741309],
       [ 0.05393216, -0.09036615,  0.05958077, ...,  1.61409446,
         1.26783305, -0.61056679]])

In [19]:
X_test_scale

array([[-1.13937764,  1.87089871,  0.47766752, ...,  3.54133433,
         5.76161263, -0.69643212],
       [-1.13937764, -0.37506589,  1.00027595, ...,  0.06195497,
         1.12258556,  0.41981711],
       [ 0.65058706,  1.39639915, -0.04494092, ...,  0.20423442,
         0.45859702,  1.36433569],
       ...,
       [ 0.94891451,  0.13106698,  0.89575427, ...,  0.72161425,
        -0.51070768,  1.53606634],
       [-1.13937764, -1.35569832,  1.00027595, ...,  0.63107278,
        -0.12535719, -1.03989342],
       [ 0.35225961, -1.10263188, -0.04494092, ..., -0.23553843,
        -0.33285361, -0.78229744]])

In [20]:
mvc_model = SVMC(learning_rate=0.01, epochs=10, lambda_value=0.1)

In [21]:
mvc_model.fit(X=X_train_scale, y=y_train)

In [22]:
y_pred = mvc_model.predict(X=X_test_scale)
y_pred

array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
mvc_model.coef_

array([ 0.14903682,  0.53148335, -0.12069242, -0.09621835,  0.02380761,
        0.18229611,  0.05044588,  0.08554633])

In [24]:
mvc_model.intercept_

0.7600000000000005

In [25]:
confusion_matrix(y_true=y_test, y_pred=y_pred)

array([[96,  4],
       [31, 23]], dtype=int64)

In [33]:
accuracy_score(y_true=y_test, y_pred=y_pred)

0.7727272727272727

## Using sklearn svm

In [26]:
model = SVC()

In [27]:
model.fit(X=X_train_scale, y=y_train)

SVC()

In [28]:
model.intercept_

array([-0.09190971])

In [29]:
# model.coef_

In [30]:
sklearn_y_pred = model.predict(X=X_test_scale)
sklearn_y_pred

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [31]:
confusion_matrix(y_true=y_test, y_pred=sklearn_y_pred)

array([[90, 10],
       [27, 27]], dtype=int64)

In [34]:
accuracy_score(y_true=y_test, y_pred=sklearn_y_pred)

0.7597402597402597